---
galaxy_info:
  author: Gaetan Trellu (goldyfruit)
  description: Deploy a Corosync cluster, support unicast and multicast with mutilple rings
  company: InCloudUs

  issue_tracker_url: https://github.com/uoi-io/ansible-corosync/issues
  license: Apache

  min_ansible_version: 2.0

  github_branch: master

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 21
    - 22
    - 23
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
    - wily

  galaxy_tags:
    - cloud
    - clustering
    - system

dependencies: []
